# Site settings
title: Wendi Sang
description: 'Business Card Page'
url: 'https://www.zuehlke.cloud'
baseurl: ''
profilepic: '/images/touxiang.jpg'
bkimage: '/images/bk3.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Wendi Sang'
  email: sangwendi@163.com
  orcid: 0009-0005-6486-3168
  # twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  Sangwendi
  # linkedin_username:  thomas-zühlke-889182165
  # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
